// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: balancer/BalanceRespBean.proto

package com.imapi.bean.balance;

public  class BalanceRespBean {
	private byte type;
	private String resp;
	public byte getType() {
		return type;
	}
	public void setType(byte type) {
		this.type = type;
	}
	public String getResp() {
		return resp;
	}
	public void setResp(String resp) {
		this.resp = resp;
	}
}
