// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: balancer/BalanceReqBean.proto

package com.imapi.bean.balance;

public  class BalanceReqBean {
	private byte type;
	private String req;
	public byte getType() {
		return type;
	}
	public void setType(byte type) {
		this.type = type;
	}
	public String getReq() {
		return req;
	}
	public void setReq(String req) {
		this.req = req;
	}
}
