// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.IMBalancer.b2;

public final class FirstExample {
  private FirstExample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqBeanOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;
    /**
     * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
     *
     * <pre>
     *请求数据   
     * </pre>
     */
    boolean hasRequestData();
    /**
     * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
     *
     * <pre>
     *请求数据   
     * </pre>
     */
    com.IMBalancer.b2.FirstExample.ReqBean.ReqData getRequestData();
    /**
     * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
     *
     * <pre>
     *请求数据   
     * </pre>
     */
    com.IMBalancer.b2.FirstExample.ReqBean.ReqDataOrBuilder getRequestDataOrBuilder();
  }
  /**
   * Protobuf type {@code com.IMBalancer.b2.ReqBean}
   */
  public static final class ReqBean extends
      com.google.protobuf.GeneratedMessage
      implements ReqBeanOrBuilder {
    // Use ReqBean.newBuilder() to construct.
    private ReqBean(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqBean(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqBean defaultInstance;
    public static ReqBean getDefaultInstance() {
      return defaultInstance;
    }

    public ReqBean getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              com.IMBalancer.b2.FirstExample.ReqBean.ReqData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = requestData_.toBuilder();
              }
              requestData_ = input.readMessage(com.IMBalancer.b2.FirstExample.ReqBean.ReqData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(requestData_);
                requestData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.IMBalancer.b2.FirstExample.internal_static_com_IMBalancer_b2_ReqBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.IMBalancer.b2.FirstExample.internal_static_com_IMBalancer_b2_ReqBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.IMBalancer.b2.FirstExample.ReqBean.class, com.IMBalancer.b2.FirstExample.ReqBean.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqBean> PARSER =
        new com.google.protobuf.AbstractParser<ReqBean>() {
      public ReqBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqBean(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqBean> getParserForType() {
      return PARSER;
    }

    public interface ReqDataOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string data = 1;
      /**
       * <code>required string data = 1;</code>
       */
      boolean hasData();
      /**
       * <code>required string data = 1;</code>
       */
      java.lang.String getData();
      /**
       * <code>required string data = 1;</code>
       */
      com.google.protobuf.ByteString
          getDataBytes();
    }
    /**
     * Protobuf type {@code com.IMBalancer.b2.ReqBean.ReqData}
     */
    public static final class ReqData extends
        com.google.protobuf.GeneratedMessage
        implements ReqDataOrBuilder {
      // Use ReqData.newBuilder() to construct.
      private ReqData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private ReqData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final ReqData defaultInstance;
      public static ReqData getDefaultInstance() {
        return defaultInstance;
      }

      public ReqData getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private ReqData(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                data_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.IMBalancer.b2.FirstExample.internal_static_com_IMBalancer_b2_ReqBean_ReqData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.IMBalancer.b2.FirstExample.internal_static_com_IMBalancer_b2_ReqBean_ReqData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.IMBalancer.b2.FirstExample.ReqBean.ReqData.class, com.IMBalancer.b2.FirstExample.ReqBean.ReqData.Builder.class);
      }

      public static com.google.protobuf.Parser<ReqData> PARSER =
          new com.google.protobuf.AbstractParser<ReqData>() {
        public ReqData parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqData(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<ReqData> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string data = 1;
      public static final int DATA_FIELD_NUMBER = 1;
      private java.lang.Object data_;
      /**
       * <code>required string data = 1;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string data = 1;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string data = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        data_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasData()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getDataBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getDataBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.IMBalancer.b2.FirstExample.ReqBean.ReqData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.IMBalancer.b2.FirstExample.ReqBean.ReqData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.IMBalancer.b2.FirstExample.ReqBean.ReqData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.IMBalancer.b2.FirstExample.ReqBean.ReqData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.IMBalancer.b2.FirstExample.ReqBean.ReqData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.IMBalancer.b2.FirstExample.ReqBean.ReqData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.IMBalancer.b2.FirstExample.ReqBean.ReqData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.IMBalancer.b2.FirstExample.ReqBean.ReqData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.IMBalancer.b2.FirstExample.ReqBean.ReqData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.IMBalancer.b2.FirstExample.ReqBean.ReqData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.IMBalancer.b2.FirstExample.ReqBean.ReqData prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.IMBalancer.b2.ReqBean.ReqData}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.IMBalancer.b2.FirstExample.ReqBean.ReqDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.IMBalancer.b2.FirstExample.internal_static_com_IMBalancer_b2_ReqBean_ReqData_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.IMBalancer.b2.FirstExample.internal_static_com_IMBalancer_b2_ReqBean_ReqData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.IMBalancer.b2.FirstExample.ReqBean.ReqData.class, com.IMBalancer.b2.FirstExample.ReqBean.ReqData.Builder.class);
        }

        // Construct using com.IMBalancer.b2.FirstExample.ReqBean.ReqData.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          data_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.IMBalancer.b2.FirstExample.internal_static_com_IMBalancer_b2_ReqBean_ReqData_descriptor;
        }

        public com.IMBalancer.b2.FirstExample.ReqBean.ReqData getDefaultInstanceForType() {
          return com.IMBalancer.b2.FirstExample.ReqBean.ReqData.getDefaultInstance();
        }

        public com.IMBalancer.b2.FirstExample.ReqBean.ReqData build() {
          com.IMBalancer.b2.FirstExample.ReqBean.ReqData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.IMBalancer.b2.FirstExample.ReqBean.ReqData buildPartial() {
          com.IMBalancer.b2.FirstExample.ReqBean.ReqData result = new com.IMBalancer.b2.FirstExample.ReqBean.ReqData(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.data_ = data_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.IMBalancer.b2.FirstExample.ReqBean.ReqData) {
            return mergeFrom((com.IMBalancer.b2.FirstExample.ReqBean.ReqData)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.IMBalancer.b2.FirstExample.ReqBean.ReqData other) {
          if (other == com.IMBalancer.b2.FirstExample.ReqBean.ReqData.getDefaultInstance()) return this;
          if (other.hasData()) {
            bitField0_ |= 0x00000001;
            data_ = other.data_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasData()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.IMBalancer.b2.FirstExample.ReqBean.ReqData parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.IMBalancer.b2.FirstExample.ReqBean.ReqData) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string data = 1;
        private java.lang.Object data_ = "";
        /**
         * <code>required string data = 1;</code>
         */
        public boolean hasData() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string data = 1;</code>
         */
        public java.lang.String getData() {
          java.lang.Object ref = data_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            data_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string data = 1;</code>
         */
        public com.google.protobuf.ByteString
            getDataBytes() {
          java.lang.Object ref = data_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            data_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string data = 1;</code>
         */
        public Builder setData(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string data = 1;</code>
         */
        public Builder clearData() {
          bitField0_ = (bitField0_ & ~0x00000001);
          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }
        /**
         * <code>required string data = 1;</code>
         */
        public Builder setDataBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          data_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.IMBalancer.b2.ReqBean.ReqData)
      }

      static {
        defaultInstance = new ReqData(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.IMBalancer.b2.ReqBean.ReqData)
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;
    public static final int REQUESTDATA_FIELD_NUMBER = 2;
    private com.IMBalancer.b2.FirstExample.ReqBean.ReqData requestData_;
    /**
     * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
     *
     * <pre>
     *请求数据   
     * </pre>
     */
    public boolean hasRequestData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
     *
     * <pre>
     *请求数据   
     * </pre>
     */
    public com.IMBalancer.b2.FirstExample.ReqBean.ReqData getRequestData() {
      return requestData_;
    }
    /**
     * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
     *
     * <pre>
     *请求数据   
     * </pre>
     */
    public com.IMBalancer.b2.FirstExample.ReqBean.ReqDataOrBuilder getRequestDataOrBuilder() {
      return requestData_;
    }

    private void initFields() {
      name_ = "";
      requestData_ = com.IMBalancer.b2.FirstExample.ReqBean.ReqData.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRequestData()) {
        if (!getRequestData().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, requestData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, requestData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.IMBalancer.b2.FirstExample.ReqBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.IMBalancer.b2.FirstExample.ReqBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.IMBalancer.b2.FirstExample.ReqBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.IMBalancer.b2.FirstExample.ReqBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.IMBalancer.b2.FirstExample.ReqBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.IMBalancer.b2.FirstExample.ReqBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.IMBalancer.b2.FirstExample.ReqBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.IMBalancer.b2.FirstExample.ReqBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.IMBalancer.b2.FirstExample.ReqBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.IMBalancer.b2.FirstExample.ReqBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.IMBalancer.b2.FirstExample.ReqBean prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.IMBalancer.b2.ReqBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.IMBalancer.b2.FirstExample.ReqBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.IMBalancer.b2.FirstExample.internal_static_com_IMBalancer_b2_ReqBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.IMBalancer.b2.FirstExample.internal_static_com_IMBalancer_b2_ReqBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.IMBalancer.b2.FirstExample.ReqBean.class, com.IMBalancer.b2.FirstExample.ReqBean.Builder.class);
      }

      // Construct using com.IMBalancer.b2.FirstExample.ReqBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRequestDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (requestDataBuilder_ == null) {
          requestData_ = com.IMBalancer.b2.FirstExample.ReqBean.ReqData.getDefaultInstance();
        } else {
          requestDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.IMBalancer.b2.FirstExample.internal_static_com_IMBalancer_b2_ReqBean_descriptor;
      }

      public com.IMBalancer.b2.FirstExample.ReqBean getDefaultInstanceForType() {
        return com.IMBalancer.b2.FirstExample.ReqBean.getDefaultInstance();
      }

      public com.IMBalancer.b2.FirstExample.ReqBean build() {
        com.IMBalancer.b2.FirstExample.ReqBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.IMBalancer.b2.FirstExample.ReqBean buildPartial() {
        com.IMBalancer.b2.FirstExample.ReqBean result = new com.IMBalancer.b2.FirstExample.ReqBean(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (requestDataBuilder_ == null) {
          result.requestData_ = requestData_;
        } else {
          result.requestData_ = requestDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.IMBalancer.b2.FirstExample.ReqBean) {
          return mergeFrom((com.IMBalancer.b2.FirstExample.ReqBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.IMBalancer.b2.FirstExample.ReqBean other) {
        if (other == com.IMBalancer.b2.FirstExample.ReqBean.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasRequestData()) {
          mergeRequestData(other.getRequestData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (hasRequestData()) {
          if (!getRequestData().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.IMBalancer.b2.FirstExample.ReqBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.IMBalancer.b2.FirstExample.ReqBean) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;
      private com.IMBalancer.b2.FirstExample.ReqBean.ReqData requestData_ = com.IMBalancer.b2.FirstExample.ReqBean.ReqData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.IMBalancer.b2.FirstExample.ReqBean.ReqData, com.IMBalancer.b2.FirstExample.ReqBean.ReqData.Builder, com.IMBalancer.b2.FirstExample.ReqBean.ReqDataOrBuilder> requestDataBuilder_;
      /**
       * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
       *
       * <pre>
       *请求数据   
       * </pre>
       */
      public boolean hasRequestData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
       *
       * <pre>
       *请求数据   
       * </pre>
       */
      public com.IMBalancer.b2.FirstExample.ReqBean.ReqData getRequestData() {
        if (requestDataBuilder_ == null) {
          return requestData_;
        } else {
          return requestDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
       *
       * <pre>
       *请求数据   
       * </pre>
       */
      public Builder setRequestData(com.IMBalancer.b2.FirstExample.ReqBean.ReqData value) {
        if (requestDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          requestData_ = value;
          onChanged();
        } else {
          requestDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
       *
       * <pre>
       *请求数据   
       * </pre>
       */
      public Builder setRequestData(
          com.IMBalancer.b2.FirstExample.ReqBean.ReqData.Builder builderForValue) {
        if (requestDataBuilder_ == null) {
          requestData_ = builderForValue.build();
          onChanged();
        } else {
          requestDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
       *
       * <pre>
       *请求数据   
       * </pre>
       */
      public Builder mergeRequestData(com.IMBalancer.b2.FirstExample.ReqBean.ReqData value) {
        if (requestDataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              requestData_ != com.IMBalancer.b2.FirstExample.ReqBean.ReqData.getDefaultInstance()) {
            requestData_ =
              com.IMBalancer.b2.FirstExample.ReqBean.ReqData.newBuilder(requestData_).mergeFrom(value).buildPartial();
          } else {
            requestData_ = value;
          }
          onChanged();
        } else {
          requestDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
       *
       * <pre>
       *请求数据   
       * </pre>
       */
      public Builder clearRequestData() {
        if (requestDataBuilder_ == null) {
          requestData_ = com.IMBalancer.b2.FirstExample.ReqBean.ReqData.getDefaultInstance();
          onChanged();
        } else {
          requestDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
       *
       * <pre>
       *请求数据   
       * </pre>
       */
      public com.IMBalancer.b2.FirstExample.ReqBean.ReqData.Builder getRequestDataBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRequestDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
       *
       * <pre>
       *请求数据   
       * </pre>
       */
      public com.IMBalancer.b2.FirstExample.ReqBean.ReqDataOrBuilder getRequestDataOrBuilder() {
        if (requestDataBuilder_ != null) {
          return requestDataBuilder_.getMessageOrBuilder();
        } else {
          return requestData_;
        }
      }
      /**
       * <code>optional .com.IMBalancer.b2.ReqBean.ReqData requestData = 2;</code>
       *
       * <pre>
       *请求数据   
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.IMBalancer.b2.FirstExample.ReqBean.ReqData, com.IMBalancer.b2.FirstExample.ReqBean.ReqData.Builder, com.IMBalancer.b2.FirstExample.ReqBean.ReqDataOrBuilder> 
          getRequestDataFieldBuilder() {
        if (requestDataBuilder_ == null) {
          requestDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.IMBalancer.b2.FirstExample.ReqBean.ReqData, com.IMBalancer.b2.FirstExample.ReqBean.ReqData.Builder, com.IMBalancer.b2.FirstExample.ReqBean.ReqDataOrBuilder>(
                  requestData_,
                  getParentForChildren(),
                  isClean());
          requestData_ = null;
        }
        return requestDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.IMBalancer.b2.ReqBean)
    }

    static {
      defaultInstance = new ReqBean(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.IMBalancer.b2.ReqBean)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_IMBalancer_b2_ReqBean_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_IMBalancer_b2_ReqBean_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_IMBalancer_b2_ReqBean_ReqData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_IMBalancer_b2_ReqBean_ReqData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\021com.IMBalancer.b2\"i\n\007ReqBe" +
      "an\022\014\n\004name\030\001 \002(\t\0227\n\013requestData\030\002 \001(\0132\"." +
      "com.IMBalancer.b2.ReqBean.ReqData\032\027\n\007Req" +
      "Data\022\014\n\004data\030\001 \002(\tB!\n\021com.IMBalancer.b2B" +
      "\014FirstExample"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_IMBalancer_b2_ReqBean_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_IMBalancer_b2_ReqBean_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_IMBalancer_b2_ReqBean_descriptor,
              new java.lang.String[] { "Name", "RequestData", });
          internal_static_com_IMBalancer_b2_ReqBean_ReqData_descriptor =
            internal_static_com_IMBalancer_b2_ReqBean_descriptor.getNestedTypes().get(0);
          internal_static_com_IMBalancer_b2_ReqBean_ReqData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_IMBalancer_b2_ReqBean_ReqData_descriptor,
              new java.lang.String[] { "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
