// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: balancer/resp/LoginnerConnRespBean.proto

package com.imapi.bean.balance.resp;

import java.util.List;

public  class LoginnerConnRespBean {
	private int seq;
	private List<String> connList;
	public int getSeq() {
		return seq;
	}
	public void setSeq(int seq) {
		this.seq = seq;
	}
	public List<String> getConnList() {
		return connList;
	}
	public void setConnList(List<String> connList) {
		this.connList = connList;
	}
}
