// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginer/req/LoginerConnOtherReqBean.proto

package com.imapi.bean.loginer.req;

public  class LoginerConnOtherReqBean {
	private String ipPort;
	private String ip;
	private int port;
	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public int getPort() {
		return port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	public String getIpPort() {
		return ipPort;
	}

	public void setIpPort(String ipPort) {
		this.ipPort = ipPort;
	}
}
