// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: balancer/req/LoginerConnOtherSuccReqBean.proto

package com.imapi.bean.balance.req;

public  class LoginerConnOtherSuccReqBean {
	private int seq;

	public int getSeq() {
		return seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}
}
