// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: balancer/req/LoginerConnReqBean.proto

package com.imapi.bean.balance.req;

public  class LoginerConnReqBean {
	private String ip;
	private int port;
	public String getIp() {
		return ip;
	}
	public void setIp(String ip) {
		this.ip = ip;
	}
	public int getPort() {
		return port;
	}
	public void setPort(int port) {
		this.port = port;
	}
}
