// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginer/LoginerRespBean.proto

package com.imapi.bean.loginer;

public  class LoginerRespBean {
	private byte type;
	private String resp;
	public byte getType() {
		return type;
	}
	public void setType(byte type) {
		this.type = type;
	}
	public String getResp() {
		return resp;
	}
	public void setResp(String resp) {
		this.resp = resp;
	}
}
