// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginer/LoginerReqBean.proto

package com.imapi.bean.loginer;

public  class LoginerReqBean {
	private byte type;
	private String req;
	public byte getType() {
		return type;
	}
	public void setType(byte type) {
		this.type = type;
	}
	public String getReq() {
		return req;
	}
	public void setReq(String req) {
		this.req = req;
	}
}
