// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginer/resp/LoginerConnSuccRespBean.proto

package com.imapi.bean.loginer.resp;

public  class LoginerConnSuccRespBean {

	private String ipPort;
	
	public String getIpPort() {
		return ipPort;
	}
	public void setIpPort(String ipPort) {
		this.ipPort = ipPort;
	}
}
